volumes:
  certs:
  vhostd:
  html:

services:
  backend:
    image: ghcr.io/freuwort/helium-backend:latest
    env_file: .env
    environment:
      - VIRTUAL_HOST=${APP_DOMAIN}
      - LETSENCRYPT_HOST=${APP_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ./backend-storage:/var/www/html/storage
    networks:
      - helium
    depends_on:
      mysql: 
        condition: service_healthy
      redis:
        condition: service_healthy

  backend-queue:
    image: ghcr.io/freuwort/helium-backend:latest
    env_file: .env
    entrypoint: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    volumes:
      - ./backend-storage:/var/www/html/storage
    networks:
      - helium
    depends_on:
      - backend

  frontend:
    image: ghcr.io/freuwort/helium-frontend:latest
    env_file: .env
    environment:
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}
      - LETSENCRYPT_HOST=${FRONTEND_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - NUXT_PUBLIC_BACKEND_URL=${APP_URL}
      - NUXT_PUBLIC_FRONTEND_URL=${FRONTEND_URL}
      - NUXT_PUBLIC_WEBSITE_URL=${WEBSITE_URL}
      - NUXT_PUBLIC_SCREENS_URL=${SCREENS_URL}
    networks:
      - helium
    depends_on:
      - backend

  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - helium

  acme-companion:
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - helium
    depends_on:
      - nginx-proxy